{% set name = "autogluon.core" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54eb1b144cbf6980d6fb34d1ccb870f486c3ed9086d9d6e1ff84554e5cab858a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./core -vv
  number: 0
  script_env:
    - RELEASE=1

requirements:
  # adds osx_arm64 builds. See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.29                    # [build_platform != target_platform]
  host:
    - python >=3.8,<3.12
    - pip
  # see https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - matplotlib-base
    - python >=3.8,<3.12
    - numpy <1.29,>=1.21
    - scipy <1.13,>=1.5.4
    - scikit-learn <1.4.1,>=1.3.0 # >=1.3 conflicts with pytorch cuda version
    - networkx <4,>=3.0
    - pandas <2.3.0,>=2.0.0
    - tqdm <5,>=4.38
    - requests
    - matplotlib
    - boto3 <2,>=1.10
    - autogluon.common ==1.1.1
    - ray-default >=2.10.0,<2.12  # increase upper bound due to 2.10 not discoverable by osx py310
    - ray-tune >=2.10.0,<2.12  # increase upper bound due to 2.10 not discoverable by osx py310 
    - hyperopt >=0.2.7,<0.2.8

test:
  imports:
    - autogluon.core
  commands:
    - python -c "from autogluon.core import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.core
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
