{% set name = "autogluon.core" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://autogluon.s3.us-west-2.amazonaws.com/tarballs/tarball.tar.gz  
  sha256: ab3ed144bdc7693b6cc869e7f2879856ac489122663812ac1af122fbd5cb4496 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./core -vv
  number: 5
  script_env:
    - RELEASE=1

requirements:
  # adds osx_arm64 builds. See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.29                    # [build_platform != target_platform]
  host:
    - python >=3.8,<3.13
    - pip
  # see https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py
  run:
    - python >=3.8,<3.13
    - numpy >=1.21,<1.29
    - scipy >=1.5.4,<1.15
    - scikit-learn >=1.3,<1.6  
    - networkx >=3.0,<4
    - pandas >=2.0.0,<2.3.0
    - tqdm >=4.38,<5
    - requests
    - matplotlib-base
    - boto3 >=1.10,<2
    - autogluon.common =={{ version }}
    - ray-default >=2.10.0,<2.38  # increase upper bound due to 2.10 not discoverable by osx py310
    - ray-tune >=2.10.0,<2.38  # increase upper bound due to 2.10 not discoverable by osx py310 
    - hyperopt >=0.2.7,<0.2.8 

test:
  imports:
    - autogluon.core
  commands:
    - python -c "from autogluon.core import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.core
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - suzhoum
    - tonyhoo
    - giswqs
    - Innixma
